### ISSUE TITLE
NOT A BUG: I love the new @change directive! I would also love to see an @input directive at some point.

### ISSUE THREAD

**Issue by JaymanMDev** [YoeriNijs/vienna#4]

**Comment by YoeriNijs** [comment]
Nice! You would like to have an input directive instead of `someInput="someValue"`?

**Comment by JaymanMDev** [comment]
> 

It may make more sense. What does someInput="someValue" do?
Also, another thing I would like is a computed property thing, similar to computed in Vue or Memo in React.

**Comment by YoeriNijs** [comment]
Vienna is able to 'bind' the someInput from the parent template with someInput in a child component if you decorate it with the VProp decorator (see readme). I am not familiar with Vue or React, but I'll dive into this. Also, if you have some time and want to improve this framework, you are always welcome to create a PR to add this! For me, it is just one big adventure ;)

**Comment by JaymanMDev** [comment]
Okay, yeah. In that case, I feel like an @input directive may be better suited to match the other ones.

**Comment by YoeriNijs** [comment]
Not sure if the @input suits the best for input binding, since the @-mark is used for outputs now (@click, @change, @emit and so on). I think we need to make a distinction between inputs and outputs (like Angular; Angular uses square brackets for inputs and parentheses for outputs). What do you think of using the hash sign for inputs, just like `#input='someInputValue'`?

**Comment by YoeriNijs** [comment]
Added in release 0.2.0.
